name: Coverity Scan

on: push

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-latest

    env:
      COVERITY: coverity_tool

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Download Coverity distribution md5sum for cache key
        run: echo ping > ${RUNNER_TEMP}/coverity_tool.md5

      - name: Cache pull Coverity distribution, extracted
        id: cache-pull-coverity-distribution
        uses: actions/cache@v4
        with:
          path: ${{ env.COVERITY }}
          key: ${{ runner.os }}-coverity-${{ hashFiles('${{ runner.temp }}/coverity_tool.md5') }}

      - name: Download and extract Coverity distribution if cache-miss
        if: steps.cache-pull-coverity-distribution.outputs.cache-hit != 'true'
        run: |
          echo hash files ${{ hashFiles('${{ runner.temp }}/coverity_tool.md5') }}
